# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    custom_components.hacs: debug
    aiogithubapi: debug
    custom_components.kumo: debug

http:
  ssl_certificate: /config/letsencrypt/live/hillzere.com/fullchain.pem
  ssl_key: /config/letsencrypt/live/hillzere.com/privkey.pem

google_assistant:
  project_id: inspired-gear-368219
  service_account: !include SERVICE_ACCOUNT.json
  report_state: true
